### ISSUE TITLE
findLocalTool semver support (not just maj, min, patch)

### ISSUE THREAD

**Issue by ShreyasRmsft** [Microsoft/vsts-task-tool-lib#20]
When I provide the version to search for in the cache as 'x' it fails to match with pre-release versions of nuget packages. These packages have folder names as follows: x.y.z-preview-date

The function used for matching the versionSpec ( semver.satisfies() ) only matches major, minor and patch version. If there is any text after the patch version then it treats it as a no match.

Right now our nuget package is only available as a pre-release version and the cache lookup always fails.

Please let me know if you plan on fixing this.

Thanks

**Comment by bryanmacfarlane** [comment]
I will look at it.  I think it might be the responsibility of the task to get into our cache format (it's not a nuget cache) but I will re-evaluate since we could say our cache format is semver

**Comment by ShreyasRmsft** [comment]
Any updates on this? I have a fix in mind where we can trim the version down to semver and then do a match.

**Comment by bryanmacfarlane** [comment]
@ShreyasRmsft - this is on our backlog.  Without full semver support, the correct action is to 'convert' to the supported maj.min.patch

**Comment by stephenmichaelf** [comment]
I did some reading [here](https://semver.org/)

It looks like the specification is:

"Precedence for two pre-release versions with the same major, minor, and patch version MUST be determined by comparing each dot separated identifier from left to right until a difference is found as follows: identifiers consisting of only digits are compared numerically and identifiers with letters or hyphens are compared lexically in ASCII sort order. Numeric identifiers always have lower precedence than non-numeric identifiers. A larger set of pre-release fields has a higher precedence than a smaller set, if all of the preceding identifiers are equal. Example: 1.0.0-alpha < 1.0.0-alpha.1 < 1.0.0-alpha.beta < 1.0.0-beta < 1.0.0-beta.2 < 1.0.0-beta.11 < 1.0.0-rc.1 < 1.0.0."

And some more notes from an Issue in the npm package [here](https://github.com/npm/node-semver/issues/130).

**Comment by stephenmichaelf** [comment]
And here:

https://github.com/protyposis/node-semver/blob/aaba7103e1837c4ecbfe8aff956d08adf67240a1/README.md#prerelease-tags

**Comment by ShreyasRmsft** [comment]
@stephenmichaelf 

https://github.com/protyposis/node-semver/blob/aaba7103e1837c4ecbfe8aff956d08adf67240a1/README.md#prerelease-tags 

This accurately describes what we're trying to do. Basically our scenario is such that the user specified a version but we fail to fetch it for him for any reason (an infra failure on our end or maybe an error on his part) we want to get latest version (pre-release or otherwise) cached. And us being completely agnostic of what that version might be cannot hardcode a major version (say 1.*) while we look for it. '*' Would be the ideal way to say get me the latest that you have cached (pre-rel or otherwise).

**Comment by bryanmacfarlane** [comment]
We should note that a tool will never have the same maj.min.patch that differs only by the semver text portion.  In other words, maj.min.patch is distinct.  You will never have 1.2.3 and 1.2.3-beta or 1.2.3-released.  There is just one 1.2.3 and you can decorate it with text (for pre release etc...).

So, what I'm getting at is instead of you having to strip the text portion before comparing/searching, our tool lib should probably do it before we call the semver lib.

**Comment by ShreyasRmsft** [comment]
@bryanmacfarlane 

Hmm. The nuget package that we are trying to consume did not adhere to those rules. Please take a look at https://dotnet.myget.org/feed/vstest/package/nuget/Microsoft.TestPlatform

But what you say makes sense. If we could get the package to follow the above mentioned convention then the solution you suggested should work

**Comment by stephenmichaelf** [comment]
@bryanmacfarlane For the semver specification it seems like there is a discrepancy. According to their documentation things can have the same major.minor.patch with only the pre-release tag being different. One of their examples is: "For example, the range >1.2.3-alpha.3 would be allowed to match the version 1.2.3-alpha.7". Unless the discrepancy is that we know this but our code doesn't accommodate full semver.

@ShreyasRmsft For the versionSpec are you using something like ">15.6.0-preview-20171023-01"?

**Comment by ShreyasRmsft** [comment]
@stephenmichaelf 

Actually our scenario is way simpler than that. The version spec I'm currently passing in the task is just '*'.
And my expectation is to get the latest version present in the cache be it a pre-release or stable version. This is sort of a fallback mechanism in case we fail find a specific version in the cache and download fails too.

**Comment by stephenmichaelf** [comment]
@ShreyasRmsft Just as an experiment, could you try changing it to ">15.0.0-ci-20160822-01"

That seems to be the oldest version they had.

I don't think they allow * for prerelease, there was a comment:

"Prereleases can include breaking changes at any time, and frequently don't even satisfy the API contracts inherent in a module, so they're excluded from any ranges that don't explicitly opt-in to a pre-release version in that chain. So, for example, it would match ~0.3.16-alpha, but that range would not be satisfied by 0.3.17-foo.1, because that is a prerelease of a different version."

I am not 100% sure this strategy will work but it seems worth a try. What I gather from that Issue on their GitHub page is that you can't use * with pre-release version matching.

**Comment by ShreyasRmsft** [comment]
@stephenmichaelf Will give this a shot and see if it works

**Comment by ShreyasRmsft** [comment]
@stephenmichaelf @bryanmacfarlane 

This didn't work. The reason being 

quoting from the semver repo:

For example, the range >1.2.3-alpha.3 would be allowed to match the version 1.2.3-alpha.7, but it would not be satisfied by 3.4.5-alpha.9, even though 3.4.5-alpha.9 is technically "greater than" 1.2.3-alpha.3 according to the SemVer sort rules. The version range only accepts prerelease tags on the 1.2.3 version.

At the moment there doesn't seem to be any way to specify get me any pre-release version of the tool.
'*' won't match pre-release versions. '>' will work for pre-releases of only a particular major-minor-patch version and not for pre-releases of other versions.

**Comment by ShreyasRmsft** [comment]
The change I wish to make is in line 88 of tool.ts:

let satisfied: boolean = semver.satisfies(potential, versionSpec);

Here just truncate potential to major.minor.patch and then do the comparison. If you're afraid doing this might be drifting away from the semver behavior, then we can add an optional parameter that says something like include pre-release versions for wild card matches or something of this sort and only if this is set we'll truncate and match if not we adhere to the semver rules.

Lemme know if this is acceptable and I'll raise a PR for it.

**Comment by ShreyasRmsft** [comment]
@stephenmichaelf @bryanmacfarlane any updates on this?

**Comment by stephenmichaelf** [comment]
@ShreyasRmsft I am apprehensive about going against the semver standard, even with a flag. Once we go down that road it adds complexity as opposed to saying "we follow semver" and we could start to hit weird edge cases. I could see an alternative where you as the consumer have a list of possible versions then make iterative calls to findLocalTool and if you find one then use it, otherwise download.

@bryanmacfarlane what do you think?

**Comment by ShreyasRmsft** [comment]
@stephenmichaelf The list of possible versions is a slippery slope either we'll have to hardcode these into the task (Which means constant manual updates every time a new version is out) or we fetch the list from somewhere and try each version (This poses a major perf issue and sorta negates the reason we are falling back to the cache to give as any version present).

**Comment by stephenmichaelf** [comment]
Here is my understanding of the use case:

It's being used in the [VsTestPlatformToolInstaller](https://github.com/Microsoft/vsts-tasks/tree/master/Tasks/VsTestPlatformToolInstaller).

Here is the UI for the tool:

![image](https://user-images.githubusercontent.com/450490/33685085-74b2d028-da9e-11e7-886f-16e100765f47.png)

The tool installer installs [Microsoft.TestPlatform](https://dotnet.myget.org/feed/vstest/package/nuget/Microsoft.TestPlatform) which uses a versioning scheme like MAJOR.MINOR.PATCH.preview-YYMMDD-REVISION#

Their latest version, for example, is 15.6.0.preview-20171204-01.

The way the tool installer works is:

1. A user specifies they want the latest version or a specific version
2. For the latest version, the installer queries Nuget for all versions, finds the latest, then looks for it in the cache. If it isn't there, the tool downloads and installs it. If this process fails, the installer looks in the cache for any available version. If nothing is found in the cache then the installer fails.

The fallback code lives [here](https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/VsTestPlatformToolInstaller/vstestplatformtoolinstaller.ts#L90).

The main issue that would cause this code path is lack of connectivity to the Nuget feed. This could fail when getting the list of all package versions or fail when downloading the package.

The team is also planning an option to get the latest available in the cache.

Part of your plan is to add retries to Nuget depending on the type of error thath happens.

The discrepancy here is that because Microsoft.TestPlatform is using the preview attribute frequently, "*" is not satisfied by any versions that may be installed in the cache.

We cannot simply ask to match on a version higher than 1.0.0 because semver does not match higher major/minor/patch versions for preview releases. For a preview to "satisfy" the major, minor, and patch must match explicitly.

**Do we persist the full version string?**
Yes we persist the full string, I ran a test and the path created was:
vsts-agent\_layout\_work\_tool\VsTest\15.6.0-preview-20171108-02
Note: not sure why it didnt get the absolute newewst one according to myget.

**Try to match on preview string using semver properly, semver npm version 4.3.3**

semver.satisfies(15.6.0-alpha.3, *) -> true
semver.satisfies(15.6.0-alpha.3, >1.0.0) -> false
semver.satisfies(15.6.0.preview-20171204-01, *) -> TypeError: Invalid Version: 15.6.0.preview-20171204-01
semver.satisfies(15.6.0.preview-20171204-01, >1.0.0) -> TypeError: Invalid Version: 15.6.0.preview-20171204-01
semver.satisfies(15.6.0, *) -> true
semver.satisfies(15.6.0, >1.0.0) -> true

If we fix the preview label:

semver.satisfies(15.6.0-preview-20171204-01, *) -> true
semver.satisfies(15.6.0-preview-20171204-01, >1.0.0) -> false

It's surprising to me that the first one(after fixing the preview label) is true but this would mean that if they were using valid semver conventions this code should work as desired by your team. The strange thing is that if I check an online checker http://jubianchi.github.io/semver-check/, it says it does not satisfy. It's posssible the online checker is not up to date.

It looks like they aren't following semantic versioning correctly, even for preview releases.

The semver site states:

"A pre-release version MAY be denoted by appending a hyphen and a series of dot separated identifiers immediately following the patch version. Identifiers MUST comprise only ASCII alphanumerics and hyphen [0-9A-Za-z-]. Identifiers MUST NOT be empty. Numeric identifiers MUST NOT include leading zeroes. Pre-release versions have a lower precedence than the associated normal version. A pre-release version indicates that the version is unstable and might not satisfy the intended compatibility requirements as denoted by its associated normal version. Examples: 1.0.0-alpha, 1.0.0-alpha.1, 1.0.0-0.3.7, 1.0.0-x.7.z.92."

Since TestPlatform is using a period after the patch version, it's not a valid semver. It would be validif it was 15.6.0-preview-20171204-01. Based on my test it would also "satisfy" passing * as the range.

@ShreyasRmsft Can you confirm all of this information is accurate?

After this research it seems like the course of action is to get the team that makes Microsoft.TestPlatform to use semver correctly.

@bryanmacfarlane @chrisrpatterson

**Comment by bryanmacfarlane** [comment]
@stephenmichaelf - Thanks for summarizing and confirming we persist the full semver and do the right thing concerning semver semantics.

@ShreyasRmsft - the scenario and task here does not follow the prescribed pattern set forth by the samples, the node installer and nuget installer tasks.  Schedule an experience review with @chrisrpatterson 

Closing this request
