### ISSUE TITLE
Cache utility accepts the sementic version 

### ISSUE THREAD

**Issue by hililh** [Microsoft/vsts-task-tool-lib#30]
Cache utility accepts the sementic version. I have a usecase where for go tool, user can enter 1.10 instead of 1.10.0. Cache utility fails because, semver function expecting patch to be available. 

Go, doent specify the patch if it doesn't available in the version list. I have to workaround currently to bypass this problem.

**Comment by stephenmichaelf** [comment]
@hililh I think the workaround on your side is the best way to address this. Semantic versioning is standard and we pass off the version checking to a library that handles it, [semver](https://www.npmjs.com/package/semver). Since this is a very specific use case of not following semantic versioning I would say it's unlikely we change the library to handle it.

@bryanmacfarlane Any other thoughts?

**Comment by stephenmichaelf** [comment]
Going to close this. Please reopen if you have further questions.
